# Generated by Django 5.2.3 on 2025-06-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_alter_attendance_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
