# Generated by Django 5.2.3 on 2025-06-28 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('total_working_days', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('Salary', models.DecimalField(decimal_places=5, max_digits=10)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
