# Generated by Django 5.2.3 on 2025-06-28 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='Salary',
            new_name='salary_amount',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='total_working_days',
            new_name='year',
        ),
        migrations.AddField(
            model_name='salary',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
