# Generated by Django 5.2.3 on 2025-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_rename_salary_salary_salary_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('department', 'Department')], default='admin', max_length=20),
        ),
    ]
