# Generated by Django 5.1.2 on 2025-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='basic_salary',
            field=models.DecimalField(decimal_places=3, default=25000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='admin', max_length=20),
        ),
    ]
