# Generated by Django 5.1.2 on 2025-07-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_customuser_basic_salary_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default='general', max_length=100),
            preserve_default=False,
        ),
    ]
